import { Component, HostListener, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { StudentService } from '../../services/student.service';
import { StudentSummary } from '../../services/student.model';
// import { ReportService } from '../../services/report.service';

export interface ArchiveReport {
  id:             string;
  name:           string;
  template:       string;
  type:           string;
  generatedBy:    string;
  date:           string;
  status:         'DONE' | 'PROCESSING' | 'FAILED';
  downloadUrl?:   string;
  failureReason?: string;
  lastDownloadedAt?: string;
  student:        StudentSummary;
}

export interface ReportBatch {
  id:             string;
  name:           string;
  template:       string;
  generatedBy:    string;
  date:           string;
  details:        string;
  status:         'DONE' | 'PROCESSING' | 'FAILED';
  generatedCount: number;
  totalCount:     number;
  lastDownloadedAt?: string;
  reports:        ArchiveReport[];
}

type StudentTypeFilter = 'ALL' | 'K12' | 'COLLEGE' | 'ADMISSIONS';

@Component({
  selector: 'app-report-archives',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './archives.html',
  styleUrl: './archives.css',
})
export class Archives implements OnInit {

  viewMode: 'batches' | 'detail' = 'batches';
  selectedBatch: ReportBatch | null = null;

  search = '';
  selectedIds = new Set<string>();
  selectedStatuses = new Set<ArchiveReport['status']>();
  selectedDateFilter: 'ALL' | 'LAST_7' | 'LAST_30' | 'THIS_MONTH' | 'CUSTOM' = 'ALL';
  customDateFrom = '';
  customDateTo = '';
  selectedStudentType: StudentTypeFilter = 'ALL';

  dropdownStates = {
    date: false,
    status: false,
  };

  // ── Search scope toggle ──
  searchFieldsOpen = false;
  searchFieldOptions = [
    { key: 'template', label: 'Template' },
    { key: 'generatedBy', label: 'Generated by' },
  ];
  enabledSearchFields = new Set<string>(['template', 'generatedBy']);

  currentPage = 1;
  pageSize = 8;

  // ── Pagination for the roster inside a batch's detail view ──
  detailPage = 1;
  detailPageSize = 10;

  // ── Sorting state for batch roster ──
  sortField: string = 'student.studentId';
  sortAsc: boolean = true;

  statusClasses: Record<ArchiveReport['status'], string> = {
    DONE: 'status-badge-done',
    PROCESSING: 'status-badge-processing',
    FAILED: 'status-badge-failed',
  };

  batches: ReportBatch[] = [];

  constructor(private authService: AuthService, private studentService: StudentService, private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    this.studentService.getAllStudents().subscribe({
      next: (students) => {
        this.batches = this.buildMockBatches(students);
        this.cdr.detectChanges();
      },
      error: (err) => console.error('Failed to load students for archives:', err),
    });
  }

  private get currentUserName(): string {
    return this.authService.getCurrentUser()?.username ?? 'You';
  }

  private buildMockBatches(students: StudentSummary[]): ReportBatch[] {
    const k12Students = students.filter(s => s.studentType === 'K12');
    const collegeStudents = students.filter(s => s.studentType === 'COLLEGE');

    return [
      {
        id: 'B-1',
        name: 'Batch 1 - Certificate of Enrollment',
        template: 'Certificate of Enrollment',
        generatedBy: this.currentUserName,
        date: '2026-06-01',
        details: 'Grade 11 • STEM • St. Jude',
        status: 'DONE',
        generatedCount: Math.min(2, k12Students.length),
        totalCount: Math.min(2, k12Students.length),
        lastDownloadedAt: '2026-06-02',
        reports: this.makeMockReports('B-1', 'Certificate of Enrollment', k12Students.slice(0, 2), 'DONE'),
      },
      {
        id: 'B-2',
        name: 'Batch 2 - Diploma Certificate',
        template: 'Diploma Certificate',
        generatedBy: this.currentUserName,
        date: '2026-05-30',
        details: 'Grade 12 • ABM • St. Thomas',
        status: 'FAILED',
        generatedCount: Math.min(1, k12Students.length),
        totalCount: Math.min(2, k12Students.slice(2, 4).length || k12Students.length),
        reports: this.makeMockReports('B-2', 'Diploma Certificate', k12Students.slice(2, 4), 'FAILED', 1),
      },
      {
        id: 'B-3',
        name: 'Batch 3 - Registrar Form 137',
        template: 'Registrar Form 137',
        generatedBy: this.currentUserName,
        date: '2026-05-28',
        details: 'College • CS & Accountancy',
        status: 'PROCESSING',
        generatedCount: Math.min(1, collegeStudents.length),
        totalCount: collegeStudents.length,
        reports: this.makeMockReports('B-3', 'Registrar Form 137', collegeStudents, 'PROCESSING', 1),
      },
    ];
  }

  private makeMockReports(batchId: string, template: string, students: StudentSummary[], status: ArchiveReport['status'], generatedOverride?: number): ArchiveReport[] {
    const generated = generatedOverride ?? students.length;
    return students.map((student, i) => ({
      id: `${batchId}-R${i + 1}`,
      name: template,
      template,
      type: 'REPORT',
      generatedBy: this.currentUserName,
      date: '2026-05-20',
      status: i < generated ? 'DONE' : status,
      downloadUrl: '#',
      failureReason: (i >= generated && status === 'FAILED') ? 'Template variable "signatory" is missing for this student.' : undefined,
      student,
    }));
  }

  get statusOptions(): ArchiveReport['status'][] {
    return ['DONE', 'FAILED', 'PROCESSING'];
  }

  // Highlights the student population a batch belongs to (K12 vs College)
  batchStudentType(batch: ReportBatch): 'K12' | 'College' {
    return batch.reports[0]?.student.studentType === 'COLLEGE' ? 'College' : 'K12';
  }

  selectStudentType(type: StudentTypeFilter): void {
    this.selectedStudentType = type;
    this.currentPage = 1;
  }

  get studentSearchResults(): { report: ArchiveReport; batch: ReportBatch }[] {
    if (!this.search.trim()) return [];
    const query = this.search.toLowerCase();
    const results: { report: ArchiveReport; batch: ReportBatch }[] = [];

    for (const batch of this.batches) {
      for (const report of batch.reports) {
        const fullName = report.student.name.toLowerCase();
        const typeLabel = report.student.studentType.toLowerCase();
        const subtitle = (report.student.subtitle ?? '').toLowerCase();
        if (
          fullName.includes(query) ||
          report.student.studentId.toLowerCase().includes(query) ||
          typeLabel.includes(query) ||
          subtitle.includes(query)
        ) {
          results.push({ report, batch });
        }
      }
    }
    return results;
  }

  jumpToStudentReport(batch: ReportBatch): void {
    this.openBatch(batch);
    this.search = '';
  }

  get filteredBatches(): ReportBatch[] {
    const query = this.search.toLowerCase();
    return this.batches.filter(batch => {
      const matchesName = batch.name.toLowerCase().includes(query);
      const matchesTemplate = this.enabledSearchFields.has('template') && batch.template.toLowerCase().includes(query);
      const matchesGeneratedBy = this.enabledSearchFields.has('generatedBy') && batch.generatedBy.toLowerCase().includes(query);
      const matchesTypeText = this.batchStudentType(batch).toLowerCase().includes(query);
      const matchesSearch = !query || matchesName || matchesTemplate || matchesGeneratedBy || matchesTypeText;

      const matchesStatus = this.selectedStatuses.size === 0 || this.selectedStatuses.has(batch.status);
      const matchesDate = this.matchesDateFilter(batch.date);
      const matchesType = this.selectedStudentType === 'ALL' ||
        (this.selectedStudentType === 'K12' && this.batchStudentType(batch) === 'K12') ||
        (this.selectedStudentType === 'COLLEGE' && this.batchStudentType(batch) === 'College');
        // ADMISSIONS currently has no batches of its own; matchesType stays false for it until that flow exists.

      return matchesSearch && matchesStatus && matchesDate && matchesType;
    });
  }

  get pageCount(): number {
    return Math.max(1, Math.ceil(this.filteredBatches.length / this.pageSize));
  }

  get pageNumbers(): number[] {
    return Array.from({ length: this.pageCount }, (_, i) => i + 1);
  }

  get pagedBatches(): ReportBatch[] {
    const start = (this.currentPage - 1) * this.pageSize;
    return this.filteredBatches.slice(start, start + this.pageSize);
  }

  get dateFilterLabel(): string {
    switch (this.selectedDateFilter) {
      case 'LAST_7': return 'Last 7 days';
      case 'LAST_30': return 'Last 30 days';
      case 'THIS_MONTH': return 'This month';
      case 'CUSTOM': return this.customDateFrom && this.customDateTo ? `${this.customDateFrom} to ${this.customDateTo}` : 'Custom range';
      default: return 'Date';
    }
  }

  get statusFilterLabel(): string {
    return this.selectedStatuses.size === 0 ? 'Status' : `${this.selectedStatuses.size} selected`;
  }

  @HostListener('document:click')
  onDocumentClick(): void {
    this.closeAllDropdowns();
  }

  toggleDropdown(type: 'date' | 'status', event: Event): void {
    event.stopPropagation();
    const next = !this.dropdownStates[type];
    this.closeAllDropdowns();
    this.dropdownStates[type] = next;
  }

  toggleSearchFieldsPanel(event: Event): void {
    event.stopPropagation();
    const next = !this.searchFieldsOpen;
    this.closeAllDropdowns();
    this.searchFieldsOpen = next;
  }

  onSearchFieldToggle(key: string): void {
    if (this.enabledSearchFields.has(key)) this.enabledSearchFields.delete(key);
    else this.enabledSearchFields.add(key);
    this.currentPage = 1;
  }

  isSearchFieldEnabled(key: string): boolean {
    return this.enabledSearchFields.has(key);
  }

  closeAllDropdowns(): void {
    this.dropdownStates = { date: false, status: false };
    this.searchFieldsOpen = false;
  }

  onDropdownClick(event: Event): void {
    event.stopPropagation();
  }

  setDateFilter(value: 'ALL' | 'LAST_7' | 'LAST_30' | 'THIS_MONTH' | 'CUSTOM'): void {
    this.selectedDateFilter = value;
    this.currentPage = 1;
  }

  formatDate(value: string): string {
    const [year, month, day] = value.split('-');
    return `${month}-${day}-${year}`;
  }

  toggleStatus(status: ArchiveReport['status']): void {
    if (this.selectedStatuses.has(status)) this.selectedStatuses.delete(status);
    else this.selectedStatuses.add(status);
    this.selectedStatuses = new Set(this.selectedStatuses);
    this.currentPage = 1;
  }

  clearFilter(type: 'status' | 'date'): void {
    if (type === 'status') this.selectedStatuses.clear();
    if (type === 'date') {
      this.selectedDateFilter = 'ALL';
      this.customDateFrom = '';
      this.customDateTo = '';
    }
    this.currentPage = 1;
  }

  matchesDateFilter(value: string): boolean {
    if (this.selectedDateFilter === 'ALL') return true;
    const date = new Date(value);
    const now = new Date();
    const beginningOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const sevenDaysAgo = new Date(now); sevenDaysAgo.setDate(now.getDate() - 7);
    const thirtyDaysAgo = new Date(now); thirtyDaysAgo.setDate(now.getDate() - 30);

    if (this.selectedDateFilter === 'LAST_7') return date >= sevenDaysAgo;
    if (this.selectedDateFilter === 'LAST_30') return date >= thirtyDaysAgo;
    if (this.selectedDateFilter === 'THIS_MONTH') return date >= beginningOfMonth;
    if (this.selectedDateFilter === 'CUSTOM') {
      if (!this.customDateFrom || !this.customDateTo) return true;
      const from = new Date(this.customDateFrom);
      const to = new Date(this.customDateTo);
      to.setHours(23, 59, 59, 999);
      return date >= from && date <= to;
    }
    return true;
  }

  openBatch(batch: ReportBatch): void {
    this.selectedBatch = batch;
    this.viewMode = 'detail';
    this.selectedIds.clear();
    this.detailPage = 1;
  }

  backToBatches(): void {
    this.viewMode = 'batches';
    this.selectedBatch = null;
    this.selectedIds.clear();
  }

  // ── Roster sorting and pagination within a batch's detail view ──

  sort(field: string): void {
    if (this.sortField === field) {
      this.sortAsc = !this.sortAsc;
    } else {
      this.sortField = field;
      this.sortAsc = true;
    }
    this.detailPage = 1; // Return to first page on sort
  }

  // Helper to drill into nested objects like 'student.name'
  private resolveFieldValue(obj: any, path: string): any {
    return path.split('.').reduce((o, p) => (o ? o[p] : ''), obj);
  }

  get sortedReports(): ArchiveReport[] {
    if (!this.selectedBatch) return [];
    
    // Create a copy so we don't mutate the original batch data
    const reports = [...this.selectedBatch.reports];
    
    if (this.sortField) {
      reports.sort((a, b) => {
        let valA = this.resolveFieldValue(a, this.sortField);
        let valB = this.resolveFieldValue(b, this.sortField);

        // Case-insensitive string sorting
        if (typeof valA === 'string') valA = valA.toLowerCase();
        if (typeof valB === 'string') valB = valB.toLowerCase();

        if (valA < valB) return this.sortAsc ? -1 : 1;
        if (valA > valB) return this.sortAsc ? 1 : -1;
        return 0;
      });
    }
    
    return reports;
  }

  get detailPageCount(): number {
    const total = this.selectedBatch?.reports.length ?? 0;
    return Math.max(1, Math.ceil(total / this.detailPageSize));
  }

  get detailPageNumbers(): number[] {
    return Array.from({ length: this.detailPageCount }, (_, i) => i + 1);
  }

  get pagedReports(): ArchiveReport[] {
    const start = (this.detailPage - 1) * this.detailPageSize;
    return this.sortedReports.slice(start, start + this.detailPageSize);
  }

  changeDetailPage(page: number): void {
    if (page < 1 || page > this.detailPageCount) return;
    this.detailPage = page;
  }

  downloadBatch(batch: ReportBatch): void {
    console.log('Downloading entire batch', batch.id);
    batch.lastDownloadedAt = new Date().toISOString().slice(0, 10);
  }

  retryBatch(batch: ReportBatch): void { console.log('Retrying batch generation for', batch.id); }
  retryReport(report: ArchiveReport): void { console.log('Retry report generation for', report.id); }

  downloadReport(report: ArchiveReport): void {
    console.log('Downloading', report.id, report.downloadUrl);
    report.lastDownloadedAt = new Date().toISOString().slice(0, 10);
  }

  // ── Selection logic for batch detail view ──

  // Helper to get only reports that are allowed to be downloaded
  get selectableReports(): ArchiveReport[] {
    return (this.selectedBatch?.reports ?? []).filter(r => r.status !== 'PROCESSING');
  }

  get allSelected(): boolean {
    const selectable = this.selectableReports;
    return selectable.length > 0 && selectable.every(r => this.selectedIds.has(r.id));
  }

  toggleSelectAll(event: Event): void {
    const checked = (event.target as HTMLInputElement).checked;
    
    // Only iterate over selectable reports so we don't grab PROCESSING ones
    this.selectableReports.forEach(r => {
      if (checked) this.selectedIds.add(r.id);
      else this.selectedIds.delete(r.id);
    });
    this.selectedIds = new Set(this.selectedIds);
  }

  toggleRow(id: string): void {
    const report = this.selectedBatch?.reports.find(r => r.id === id);
    if (report?.status === 'PROCESSING') return; // Safety guard

    if (this.selectedIds.has(id)) this.selectedIds.delete(id);
    else this.selectedIds.add(id);
    this.selectedIds = new Set(this.selectedIds);
  }

  downloadSelected(): void {
    console.log('Batch download of selected reports', Array.from(this.selectedIds));
  }

  changePage(page: number): void {
    if (page < 1 || page > this.pageCount) return;
    this.currentPage = page;
  }
}