import { StudentType } from './student.model';

export interface School {
  id: string;       // UUID
  name?: string;     // adjust once School.java is confirmed
}

export interface ReportTemplate {
  id?: string;              // UUID, generated by backend - omit when creating
  name: string;
  configuration: string;    // JSON string from the WYSIWYG editor (stringify before sending)
  school: School;            // or use schoolId: string if backend expects a flat FK on create
  lastOpenedAt?: string;     // ISO timestamp, set by the backend whenever the template is opened
  thumbnailUrl?: string;     // set by the backend after a thumbnail is uploaded
  // Persisted once com.cssweng.reportbuilder.model.ReportTemplate (Java) and its DB column exist.
  studentType?: StudentType;
}