// Mirrors backend: com.cssweng.reportbuilder.model.ReportTemplate

export interface School {
  id: string;       // UUID
  name?: string;     // adjust once School.java is confirmed
}

export type TemplateStudentType = 'K12' | 'COLLEGE' | 'ADMISSIONS';

export interface ReportTemplate {
  id?: string;              // UUID, generated by backend — omit when creating
  name: string;
  configuration: string;    // JSON string from the WYSIWYG editor (stringify before sending)
  school: School;            // or use schoolId: string if backend expects a flat FK on create
  lastOpenedAt?: string;     // ISO timestamp, set by the backend whenever the template is opened
  thumbnailUrl?: string;     // set by the backend after a thumbnail is uploaded
  studentType?: TemplateStudentType;  // which roster this template is meant for; nullable for older templates
}

// Convenience type for POST payloads where you may only have the school's id on hand
export interface CreateReportTemplateRequest {
  name: string;
  configuration: string;
  schoolId: string;
  studentType?: TemplateStudentType;
}