// report-template.model.ts
// Mirrors backend: com.cssweng.reportbuilder.model.ReportTemplate

export interface School {
  id: string;       // UUID
  name?: string;     // adjust once School.java is confirmed
}

// Which student type this template was created for. Optional/undefined
// means "not tagged" — a legacy template saved before this field existed.
export type TemplateStudentType = 'K12' | 'COLLEGE' | 'ADMISSIONS';

export interface ReportTemplate {
  id?: string;              // UUID, generated by backend — omit when creating
  name: string;
  configuration: string;    // JSON string from the WYSIWYG editor (stringify before sending)
  school: School;            // or use schoolId: string if backend expects a flat FK on create
  lastOpenedAt?: string;     // ISO timestamp, set by the backend whenever the template is opened
  thumbnailUrl?: string;     // set by the backend after a thumbnail is uploaded
  // Persisted once com.cssweng.reportbuilder.model.ReportTemplate (Java)
  // and its DB column exist — see backend TODO. Frontend is ready.
  studentType?: TemplateStudentType;
}